services:
  - type: web
    name: kapebara
    runtime: node
    rootDir: .
    autoDeploy: true
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
